# Generated by Django 6.0.6 on 2026-09-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='local',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='longitude',
        ),
        migrations.AddField(
            model_name='evento',
            name='complemento',
            field=models.CharField(blank=True, max_length=150, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='numero',
            field=models.CharField(default='', max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='evento',
            name='rua',
            field=models.CharField(default='', max_length=200, verbose_name='Rua'),
        ),
        migrations.AddField(
            model_name='evento',
            name='setor',
            field=models.CharField(default='', max_length=100, verbose_name='Setor/Bairro'),
        ),
    ]
