# Generated by Django 5.1.15 on 2026-09-04 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_organizacao_fidelidade_ativa_and_more'),
        ('eventos', '0002_contrato_organizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='desconto_fidelidade',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Desconto Fidelidade (R$)'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='pontos_creditados',
            field=models.BooleanField(default=False, verbose_name='Pontos já creditados na carteira?'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='pontos_gerados',
            field=models.PositiveIntegerField(default=0, verbose_name='Pontos Gerados (Para o futuro)'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='pontos_utilizados',
            field=models.PositiveIntegerField(default=0, verbose_name='Pontos Utilizados (Desconto)'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Total (Base)'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='cliente',
            field=models.CharField(blank=True, max_length=200, verbose_name='Cliente / Responsável (Legado)'),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=30, verbose_name='CPF/CNPJ')),
                ('locapoints', models.PositiveIntegerField(default=0, verbose_name='LocaPoints Acumulados')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('organizacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='empresas.organizacao')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='cliente_fidelidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='eventos.cliente', verbose_name='Cliente (Sistema Fidelidade)'),
        ),
    ]
