# Generated by Django 5.1.15 on 2026-09-05 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_contrato_desconto_fidelidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, help_text='Necessário para avisos automáticos e envio de contratos', max_length=254, verbose_name='E-mail do Cliente'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
    ]
