# Generated by Django 6.0.6 on 2026-09-02 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_evento_latitude_evento_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contratante_nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('contratante_cpf_cnpj', models.CharField(max_length=30, verbose_name='CPF/CNPJ')),
                ('contratante_telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('contratante_endereco', models.CharField(max_length=300, verbose_name='Endereço')),
                ('data_montagem', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Montagem')),
                ('data_desmontagem', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Desmontagem')),
                ('endereco_montagem', models.CharField(max_length=300, verbose_name='Endereço da Montagem')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Total')),
                ('sinal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Sinal')),
                ('forma_pagamento', models.CharField(max_length=100, verbose_name='Forma de Pagamento')),
                ('itens_locados', models.TextField(verbose_name='Itens Locados')),
                ('clausulas', models.TextField(verbose_name='Cláusulas')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='eventos.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
    ]
