# Generated by Django 6.0.6 on 2026-09-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='hora_fim',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de Fim'),
        ),
        migrations.AddField(
            model_name='evento',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de Início'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='sinal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Sinal'),
        ),
    ]
