# Generated by Django 5.1.15 on 2026-09-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_alter_cliente_organizacao_alter_contrato_organizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data_fim',
            field=models.DateField(db_index=True, verbose_name='Data de Fim'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_inicio',
            field=models.DateField(db_index=True, verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='status',
            field=models.CharField(choices=[('agendado', 'Agendado'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], db_index=True, default='agendado', max_length=20, verbose_name='Status'),
        ),
    ]
