# Generated by Django 5.1.15 on 2026-09-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_contrato_data_assinatura_contrato_ip_assinatura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='data_devolucao_real',
            field=models.DateTimeField(blank=True, help_text='Preenchido caso o evento termine e os itens sejam devolvidos ANTES da Data de Desmontagem prevista.', null=True, verbose_name='Data e Hora Real de Devolução'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_fim',
            field=models.DateField(db_index=True, verbose_name='Data de Desmontagem'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='hora_fim',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de Desmontagem'),
        ),
    ]
