# Generated by Django 5.1.15 on 2026-09-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacao',
            name='clausulas_padrao',
            field=models.TextField(blank=True, default='1. RESPONSABILIDADE DO LOCAL: O Contratante é responsável por autorizações...\n2. FORÇA MAIOR: A Contratada isenta-se...', verbose_name='Cláusulas Padrão do Contrato'),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo da Empresa'),
        ),
    ]
