# Generated by Django 5.1.15 on 2026-09-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_organizacao_clausulas_padrao_organizacao_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(choices=[('dono', 'Dono/Administrador'), ('funcionario', 'Funcionário')], default='dono', max_length=20, verbose_name='Cargo na Empresa'),
        ),
    ]
