# Generated by Django 5.1.15 on 2026-09-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_usuario_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacao',
            name='cor_primaria',
            field=models.CharField(default='#FFD600', help_text='Cor tema da locadora', max_length=7, verbose_name='Cor Principal'),
        ),
    ]
