# Generated by Django 5.1.15 on 2026-09-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_organizacao_cor_primaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacao',
            name='asaas_customer_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Asaas Customer ID'),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='asaas_subscription_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Asaas Subscription ID'),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='status_assinatura',
            field=models.CharField(choices=[('trial', 'Em Teste (Trial)'), ('ativa', 'Ativa'), ('inadimplente', 'Inadimplente (Bloqueada)'), ('cancelada', 'Cancelada')], default='trial', max_length=15, verbose_name='Status da Assinatura'),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='vencimento_trial',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimento do Trial'),
        ),
        migrations.AlterField(
            model_name='organizacao',
            name='cor_primaria',
            field=models.CharField(default='#004581', help_text='Cor tema da locadora', max_length=7, verbose_name='Cor Principal'),
        ),
    ]
