# Generated by Django 5.1.15 on 2026-09-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_organizacao_asaas_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacao',
            name='fidelidade_ativa',
            field=models.BooleanField(default=True, verbose_name='Ativar LocaPoints'),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='pontos_por_real',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantos pontos o cliente ganha a cada R$ 1 pago?'),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='taxa_resgate',
            field=models.PositiveIntegerField(default=100, verbose_name='Quantos pontos equivalem a R$ 1 de desconto?'),
        ),
    ]
