# Generated by Django 5.1.15 on 2026-09-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_organizacao_codigo_indicacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacao',
            name='beneficio_ativo',
            field=models.CharField(blank=True, help_text='Ex: Embaixador Prata (-5%)', max_length=100, verbose_name='Benefício de Longevidade'),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='ciclo_pagamento',
            field=models.CharField(default='MONTHLY', max_length=10, verbose_name='Ciclo'),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='meses_pagos',
            field=models.PositiveIntegerField(default=0, verbose_name='Meses de Assinatura Pagos'),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='plano',
            field=models.CharField(choices=[('starter', 'Starter (Essencial)'), ('pro', 'Pro (Avançado)'), ('premium', 'Premium (Escala)')], default='starter', max_length=20, verbose_name='Plano Escolhido'),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='vencimento_assinatura',
            field=models.DateField(blank=True, null=True, verbose_name='Próximo Vencimento'),
        ),
        migrations.AlterField(
            model_name='organizacao',
            name='status_assinatura',
            field=models.CharField(choices=[('trial', 'Em Teste (Trial)'), ('ativa', 'Ativa'), ('inadimplente', 'Inadimplente'), ('cancelada', 'Cancelada')], default='trial', max_length=15, verbose_name='Status da Assinatura'),
        ),
    ]
