# Generated by Django 5.1.15 on 2026-09-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0010_organizacao_chave_pix'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacao',
            name='segmento',
            field=models.CharField(choices=[('tendas', 'Tendas e Estruturas'), ('som_luz', 'Som, Iluminação e Audiovisual'), ('brinquedos', 'Brinquedos Infláveis e Recreação'), ('mobiliario', 'Mobiliário (Mesas, Cadeiras, Louças)'), ('geradores', 'Geradores e Climatização'), ('multi', 'Multi-Segmento / Outros')], default='multi', max_length=20, verbose_name='Nicho de Mercado'),
        ),
    ]
