# Generated by Django 5.1.15 on 2026-09-04 21:10

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tenda',
            managers=[
                ('tenant_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
