# Generated by Django 5.1.15 on 2026-09-05 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0011_organizacao_segmento'),
        ('eventos', '0009_itemevento_remove_evento_conjuntos_and_more'),
        ('inventario', '0003_alter_conjuntopalco_organizacao_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tenda',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tenda',
            name='organizacao',
        ),
        migrations.CreateModel(
            name='CategoriaEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da Categoria')),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='empresas.organizacao')),
            ],
            options={
                'verbose_name': 'Categoria de Equipamento',
                'verbose_name_plural': 'Categorias de Equipamentos',
                'ordering': ['nome'],
                'unique_together': {('nome', 'organizacao')},
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, help_text='Ex: CAIXA-01, MESA-PLAST', max_length=30, verbose_name='Código (Opcional)')),
                ('nome', models.CharField(help_text='Ex: Cadeira de Plástico, Tenda Piramidal 5x5, Pula-pula de Castelo', max_length=150, verbose_name='Nome do Item')),
                ('quantidade_total', models.PositiveIntegerField(default=1, verbose_name='Quantidade em Estoque')),
                ('valor_diaria', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor da Diária Base (R$)')),
                ('status', models.CharField(choices=[('ativo', 'Ativo (Disponível)'), ('inativo', 'Inativo / Manutenção')], default='ativo', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.categoriaequipamento')),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='empresas.organizacao')),
            ],
            options={
                'verbose_name': 'Equipamento / Item',
                'verbose_name_plural': 'Equipamentos / Itens',
                'ordering': ['nome'],
            },
        ),
        migrations.DeleteModel(
            name='ConjuntoPalco',
        ),
        migrations.DeleteModel(
            name='Tenda',
        ),
    ]
