# Generated by Django 5.1.15 on 2026-09-09 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0012_organizacao_deletado_em_organizacao_slug_and_more'),
        ('inventario', '0004_alter_tenda_unique_together_remove_tenda_organizacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='quantidade_total',
        ),
        migrations.AddField(
            model_name='categoriaequipamento',
            name='deletado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='deletado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='quantidade_lote',
            field=models.PositiveIntegerField(default=1, help_text='Usado apenas se for rastreado por Lote', verbose_name='Quantidade em Lote'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='tipo_rastreamento',
            field=models.CharField(choices=[('lote', 'Por Lote (Quantidade)'), ('serializado', 'Único/Serializado (Patrimônio)')], default='lote', max_length=20, verbose_name='Tipo de Controle'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='nome',
            field=models.CharField(help_text='Ex: Cadeira de Plástico, Tenda Piramidal 5x5', max_length=150, verbose_name='Nome do Item'),
        ),
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deletado_em', models.DateTimeField(blank=True, null=True)),
                ('numero_serie_ou_tag', models.CharField(max_length=100, verbose_name='Número de Série / Tag ID')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('em_manutencao', 'Em Manutenção'), ('inativo', 'Inativo / Danificado')], default='disponivel', max_length=20, verbose_name='Status')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrimonios', to='inventario.equipamento')),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrimonios', to='empresas.organizacao')),
            ],
            options={
                'verbose_name': 'Patrimônio (Item Único)',
                'verbose_name_plural': 'Patrimônios',
            },
        ),
    ]
