# Generated by Django 6.0.6 on 2026-09-03 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conjuntopalco',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('manutencao', 'Em Manutenção')], default='ativo', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='tenda',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('manutencao', 'Em Manutenção')], default='ativo', max_length=20, verbose_name='Status'),
        ),
    ]
