# Generated by Django 5.1.15 on 2026-09-05 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0010_organizacao_chave_pix'),
        ('inventario', '0002_alter_tenda_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conjuntopalco',
            name='organizacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='conjuntos', to='empresas.organizacao'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conjuntopalco',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('manutencao', 'Em Manutenção'), ('baixado', 'Descartado/Vendido')], default='ativo', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='tenda',
            name='organizacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tendas', to='empresas.organizacao'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tenda',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('manutencao', 'Em Manutenção'), ('baixado', 'Descartado/Vendido')], default='ativo', max_length=20, verbose_name='Status'),
        ),
    ]
