# Generated by Django 5.1.15 on 2026-09-05 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0010_organizacao_chave_pix'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_ativo', models.BooleanField(default=False, verbose_name='Bot Ativo no WhatsApp')),
                ('numero_whatsapp', models.CharField(blank=True, help_text='Ex: 5561998542025', max_length=20, verbose_name='Número Conectado')),
                ('nome_assistente', models.CharField(default='LocaBot', max_length=50, verbose_name='Nome do Robô')),
                ('prompt_personalidade', models.TextField(default='Você é um assistente virtual de uma empresa de locação de tendas. Seja educado e focado em vendas.', verbose_name='Personalidade e Regras (Prompt)')),
                ('api_key_llm', models.CharField(blank=True, max_length=200, verbose_name='Chave API da Inteligência (OpenAI/Gemini)')),
                ('webhook_token', models.CharField(blank=True, max_length=100, verbose_name='Token de Validação do Webhook (WhatsApp)')),
                ('organizacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_ia', to='empresas.organizacao')),
            ],
            options={
                'verbose_name': 'Configuração da Inteligência Artificial',
                'verbose_name_plural': 'Configurações de IA',
            },
        ),
        migrations.CreateModel(
            name='MensagemWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone_cliente', models.CharField(max_length=20, verbose_name='Telefone do Cliente')),
                ('mensagem', models.TextField(verbose_name='Conteúdo da Mensagem')),
                ('is_bot', models.BooleanField(default=False, verbose_name='Enviado pelo Bot?')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.organizacao')),
            ],
            options={
                'ordering': ['criado_em'],
            },
        ),
    ]
