# Generated by Django 6.0.6 on 2026-09-04 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Evento')),
                ('cliente', models.CharField(max_length=200, verbose_name='Cliente / Responsável')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('rua', models.CharField(default='', max_length=200, verbose_name='Rua')),
                ('numero', models.CharField(default='', max_length=20, verbose_name='Número')),
                ('setor', models.CharField(default='', max_length=100, verbose_name='Setor/Bairro')),
                ('complemento', models.CharField(blank=True, max_length=150, verbose_name='Complemento')),
                ('cidade', models.CharField(default='Formosa', max_length=100, verbose_name='Cidade')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Horário de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Fim')),
                ('hora_fim', models.TimeField(blank=True, null=True, verbose_name='Horário de Fim')),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='agendado', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conjuntos', models.ManyToManyField(blank=True, related_name='eventos', to='inventario.conjuntopalco', verbose_name='Conjuntos de Palco/Piso')),
                ('organizacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='empresas.organizacao')),
                ('tendas', models.ManyToManyField(blank=True, related_name='eventos', to='inventario.tenda', verbose_name='Tendas')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contratante_nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('contratante_cpf_cnpj', models.CharField(max_length=30, verbose_name='CPF/CNPJ')),
                ('contratante_telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('contratante_endereco', models.CharField(max_length=300, verbose_name='Endereço')),
                ('data_montagem', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Montagem')),
                ('data_desmontagem', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Desmontagem')),
                ('endereco_montagem', models.CharField(max_length=300, verbose_name='Endereço da Montagem')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Total')),
                ('sinal', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Sinal')),
                ('forma_pagamento', models.CharField(max_length=100, verbose_name='Forma de Pagamento')),
                ('itens_locados', models.TextField(verbose_name='Itens Locados')),
                ('clausulas', models.TextField(verbose_name='Cláusulas')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='eventos.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
    ]
