# Generated by Django 5.1.15 on 2026-09-05 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0010_organizacao_chave_pix'),
        ('eventos', '0004_cliente_email_alter_evento_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='organizacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='empresas.organizacao'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contrato',
            name='organizacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='empresas.organizacao'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='organizacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='empresas.organizacao'),
            preserve_default=False,
        ),
    ]
