# Generated by Django 5.1.15 on 2026-09-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_alter_evento_data_fim_alter_evento_data_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='data_assinatura',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Assinatura'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='ip_assinatura',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP da Assinatura'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='status_assinatura',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('assinado', 'Assinado'), ('recusado', 'Recusado')], default='pendente', max_length=20, verbose_name='Status da Assinatura'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='token_assinatura',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Token Seguro de Assinatura'),
        ),
    ]
