# Generated by Django 5.1.15 on 2026-09-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_evento_data_devolucao_real_alter_evento_data_fim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade Alugada')),
                ('preco_fechado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço Total Cobrado (R$)')),
            ],
        ),
        migrations.RemoveField(
            model_name='evento',
            name='conjuntos',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='tendas',
        ),
    ]
