# Generated by Django 5.1.15 on 2026-09-05 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_itemevento_remove_evento_conjuntos_and_more'),
        ('inventario', '0004_alter_tenda_unique_together_remove_tenda_organizacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemevento',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alocacoes', to='inventario.equipamento'),
        ),
        migrations.AddField(
            model_name='itemevento',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='eventos.evento'),
        ),
    ]
