# Generated by Django 5.1.15 on 2026-09-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_itemevento_equipamento_itemevento_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='contratos_pdfs/', verbose_name='Contrato em PDF'),
        ),
    ]
