# Generated by Django 5.1.15 on 2026-09-08 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0011_contrato_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Contrato Ativo (Não Cancelado)'),
        ),
    ]
