# Generated by Django 5.1.15 on 2026-09-09 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0012_organizacao_deletado_em_organizacao_slug_and_more'),
        ('eventos', '0012_contrato_ativo'),
        ('inventario', '0005_remove_equipamento_quantidade_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='deletado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='deletado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='deletado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemevento',
            name='deletado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemevento',
            name='organizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens_evento', to='empresas.organizacao'),
        ),
        migrations.AddField(
            model_name='itemevento',
            name='patrimonio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alocacoes_serial', to='inventario.patrimonio'),
        ),
    ]
