# Generated by Django 5.1.15 on 2026-09-04 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_organizacao_fidelidade_ativa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacao',
            name='codigo_indicacao',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código de Indicação'),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='indicado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicados', to='empresas.organizacao'),
        ),
    ]
