# Generated by Django 5.1.15 on 2026-09-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0008_organizacao_beneficio_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacao',
            name='cidade',
            field=models.CharField(blank=True, help_text='Ex: São Paulo, Miami', max_length=100, verbose_name='Cidade Sede'),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='estado',
            field=models.CharField(blank=True, max_length=50, verbose_name='Estado/Província'),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='moeda',
            field=models.CharField(default='BRL', help_text='BRL, USD, EUR...', max_length=10, verbose_name='Moeda Base'),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='pais',
            field=models.CharField(default='Brasil', max_length=50, verbose_name='País'),
        ),
    ]
