# Generated by Django 5.1.15 on 2026-09-05 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0009_organizacao_cidade_organizacao_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacao',
            name='chave_pix',
            field=models.CharField(blank=True, help_text='Se preenchida, aparecerá como QR Code/Chave nos contratos.', max_length=100, verbose_name='Chave PIX (Recebimento)'),
        ),
    ]
