# Generated by Django 5.1.15 on 2026-09-09 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0011_organizacao_segmento'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacao',
            name='deletado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizacao',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True, verbose_name='Slug (URL Pública)'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='deletado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
